# Generated by Django 5.2.11 on 2026-02-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_managers_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chad_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Телеграм чат id"
            ),
        ),
    ]
