# Generated by Django 5.2.11 on 2026-03-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_tg_chad_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="tg_chad_id",
            new_name="tg_chat_id",
        ),
    ]
