# Generated by Django 6.0.2 on 2026-02-16 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        max_length=100, verbose_name="Локация выполнения привычки"
                    ),
                ),
                ("time", models.TimeField()),
                ("action", models.CharField(max_length=100, verbose_name="Действие")),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False, verbose_name="Признак приятности привычки"
                    ),
                ),
                (
                    "period",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Периодичность выполнения привычки"
                    ),
                ),
                (
                    "reward",
                    models.CharField(max_length=150, verbose_name="Вознаграждение"),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        verbose_name="Продолжительность выполнения привычки"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Признак публичности"
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_habits",
                        to="habit.habit",
                        verbose_name="Связанная привычка ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
