# Generated by Django 5.2.11 on 2026-02-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Вознаграждение"
            ),
        ),
    ]
